import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./css/globals.css";
import Header from "@/components/header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const additionalClasses = "bg-bodyColor"; // Add your additional classes here

  return (
    <html lang="en">
      <body className={`${inter.className} ${additionalClasses}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
